
#
/system/framework/framework.jar
#
/system/framework/framework.jar
,
(/system/framework/framework-graphics.jar
,
(/system/framework/framework-graphics.jar

/system/framework/ext.jar

/system/framework/ext.jar
*
&/system/framework/telephony-common.jar
*
&/system/framework/telephony-common.jar
%
!/system/framework/voip-common.jar
%
!/system/framework/voip-common.jar
$
 /system/framework/ims-common.jar
$
 /system/framework/ims-common.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
1
-/apex/com.android.i18n/javalib/core-icu4j.jar
-
)/system/framework/featurelayer-widget.jar
-
)/system/framework/featurelayer-widget.jar
 
/system/framework/hwEmui.jar
 
/system/framework/hwEmui.jar
-
)/system/framework/hwPartBasicplatform.jar
-
)/system/framework/hwPartBasicplatform.jar
-
)/system/framework/telephony-separated.jar
-
)/system/framework/telephony-separated.jar
,
(/system/framework/hwTelephony-common.jar
,
(/system/framework/hwTelephony-common.jar
)
%/system/framework/hwPartTelephony.jar
)
%/system/framework/hwPartTelephony.jar
-
)/system/framework/hwPartTelephonyVSim.jar
-
)/system/framework/hwPartTelephonyVSim.jar
-
)/system/framework/hwPartTelephonyCust.jar
-
)/system/framework/hwPartTelephonyCust.jar
7
3/system/framework/hwPartTelephonyFullnetworkOpt.jar
7
3/system/framework/hwPartTelephonyFullnetworkOpt.jar
4
0/system/framework/hwPartTelephonyTimezoneOpt.jar
4
0/system/framework/hwPartTelephonyTimezoneOpt.jar
,
(/system/framework/hwPartTelephonyOpt.jar
,
(/system/framework/hwPartTelephonyOpt.jar
(
$/system/framework/hwPartSecurity.jar
(
$/system/framework/hwPartSecurity.jar
'
#/system/framework/hwPartUserIAM.jar
'
#/system/framework/hwPartUserIAM.jar
.
*/system/framework/hwPartSecurityFaceId.jar
.
*/system/framework/hwPartSecurityFaceId.jar
&
"/system/framework/hwIms-common.jar
&
"/system/framework/hwIms-common.jar
%
!/system/framework/hwPartMedia.jar
%
!/system/framework/hwPartMedia.jar
,
(/system/framework/hwPartConnectivity.jar
,
(/system/framework/hwPartConnectivity.jar
+
'/system/framework/hwPartPowerOffice.jar
+
'/system/framework/hwPartPowerOffice.jar
4
0/system/framework/hwPartDeviceVirtualization.jar
4
0/system/framework/hwPartDeviceVirtualization.jar
*
&/system/framework/hwPartAirSharing.jar
*
&/system/framework/hwPartAirSharing.jar
*
&/system/framework/hwPartDefaultDFR.jar
*
&/system/framework/hwPartDefaultDFR.jar
#
/system/framework/hwPartDFR.jar
#
/system/framework/hwPartDFR.jar
+
'/system/framework/hwPartMagicWindow.jar
+
'/system/framework/hwPartMagicWindow.jar
(
$/system/framework/hwPartsXlayout.jar
(
$/system/framework/hwPartsXlayout.jar
&
"/system/framework/hwPartIaware.jar
&
"/system/framework/hwPartIaware.jar
#
/system/framework/hwPartMdm.jar
#
/system/framework/hwPartMdm.jar
"
/system/framework/hwPartVr.jar
"
/system/framework/hwPartVr.jar
%
!/system/framework/hwframework.jar
%
!/system/framework/hwframework.jar
(
$/system/framework/com.huawei.nfc.jar
(
$/system/framework/com.huawei.nfc.jar
2
./system/framework/org.ifaa.android.manager.jar
2
./system/framework/org.ifaa.android.manager.jar
 
/system/framework/hwperf.jar
 
/system/framework/hwperf.jar
$
 /system/framework/hwcustEmui.jar
$
 /system/framework/hwcustEmui.jar
)
%/system/framework/hwcustframework.jar
)
%/system/framework/hwcustframework.jar
%
!/system/framework/servicehost.jar
%
!/system/framework/servicehost.jar
*
&/system/framework/hwcustIms-common.jar
*
&/system/framework/hwcustIms-common.jar
0
,/system/framework/hwcustTelephony-common.jar
0
,/system/framework/hwcustTelephony-common.jar
$
 /system/framework/hwIAwareAL.jar
$
 /system/framework/hwIAwareAL.jar
"
/system/framework/tcmiface.jar
"
/system/framework/tcmiface.jar
'
#/system/framework/telephony-ext.jar
'
#/system/framework/telephony-ext.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/qcom.fmradio.jar
&
"/system/framework/QPerformance.jar
&
"/system/framework/QPerformance.jar
'
#/system/framework/UxPerformance.jar
'
#/system/framework/UxPerformance.jar
#
/system/framework/WfdCommon.jar
#
/system/framework/WfdCommon.jar
&
"/system/framework/zframework.z.jar
&
"/system/framework/zframework.z.jar