
7
3/system/framework/com.android.location.provider.jar
"
/system/framework/services.jar
*
&/system/framework/ethernet-service.jar
2
./system/framework/hwPartDefaultDFRServices.jar
$
 /system/framework/hwServices.jar
(
$/system/framework/hwWifi-service.jar
$
 /system/framework/hwSelfCure.jar
+
'/system/framework/hwWifiPro-service.jar
3
//system/framework/hwPartPowerOfficeServices.jar
0
,/system/framework/hwPartSecurityServices.jar
&
"/system/framework/hwPartCamera.jar
0
,/system/framework/hwPartEyeProtectionOpt.jar
+
'/system/framework/hwPartDFRServices.jar
5
1/system/framework/hwPartBasicplatformServices.jar
3
//system/framework/hwPartMagicWindowServices.jar
3
//system/framework/hwPartPickUpWakeScreenOpt.jar
-
)/system/framework/hwPartIawareService.jar
+
'/system/framework/hwPartMdmServices.jar
2
./system/framework/hwPartSingleHandServices.jar
)
%/system/framework/hwPartVrService.jar
8
4/system/framework/hwPartDistributedNetServiceOpt.jar
-
)/system/framework/hwPartFoldScreenOpt.jar
0
,/system/framework/hwPartStylusGestureOpt.jar
.
*/system/framework/hwPartFingerprintOpt.jar
,
(/system/framework/hwPartSideTouchOpt.jar
/
+/system/framework/hwWifiEnhance-service.jar
(
$/system/framework/hwcustServices.jar
,
(/system/framework/hwcustwifi-service.jar
0
,/system/framework/hwcustethernet-service.jar